### PR TITLE
fix: swoft-cloud/swoft/issues/1084

### LINKED ISSUE #1084: crontab 执行异常: 0点0刻的时候不执行
| Swoft version       2.0.6
| Swoole version      4.4.3
| PHP version         7.2.22
| Runtime environment  CentOS 7

crontab在执行的时候有些时间是没执行到的，例如 `0 0 0 * * *` 凌晨没执行，`0 0 * * * *` 这个时间段的每小时正常执行，但到了0点0刻的时候不执行

### PR DESCRIPTION
**Pull request by JasonYHZ**
fix: swoft-cloud/swoft/issues/1084

### CODE REVIEW

File: src/crontab/src/CrontabRegister.php [hunk 1]
```diff
@@ -68,10 +68,9 @@ public static function registerCron(string $className, string $methodName, $objA
     /**
      * @return array
      */
-    public static function getCronTasks(): array
+    public static function getCronTasks($time): array
```
Comment (inhere) [inline src/crontab/src/CrontabRegister.php]: 严格一下类型 `int $time`

**Review by inhere — APPROVED** [review]
